const $=(s)=>document.querySelector(s),$$=(s)=>[...document.querySelectorAll(s)];
function setPressed(buttons,active){buttons.forEach(b=>b.setAttribute('aria-pressed',String(b===active)))}
$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>{setPressed($$('[data-mode]'),b);$('#visual-view').hidden=b.dataset.mode!=='visual';$('#index-view').hidden=b.dataset.mode!=='index';const u=new URL(location);if(b.dataset.mode==='index')u.searchParams.set('view','index');else u.searchParams.delete('view');history.replaceState(null,'',u)}));
if(new URL(location).searchParams.get('view')==='index')$('[data-mode=index]')?.click();
$$('[data-preview]').forEach(row=>{const show=()=>{if(!matchMedia('(hover:hover) and (min-width:1001px)').matches)return;const p=$('#index-preview');p.src=row.dataset.preview;p.style.display='block'};const hide=()=>$('#index-preview').style.display='none';row.addEventListener('mouseenter',show);row.addEventListener('focus',show);row.addEventListener('mouseleave',hide);row.addEventListener('blur',hide)});
$$('[data-research]').forEach(b=>b.addEventListener('click',()=>{setPressed($$('[data-research]'),b);$('#research-map').hidden=b.dataset.research!=='map';$('#research-index').hidden=b.dataset.research!=='index'}));
const seasons={dry:{src:'assets/jakarta-dry-section.webp',alt:'Dry-season section showing elevated civic platforms and wetland systems',caption:'Dry season · Workshops, kitchens, markets, and gathering spaces form a continuous civic spine.'},flood:{src:'assets/jakarta-flood-section.webp',alt:'Flood-season section showing rising water, floating shelters, and elevated refuge',caption:'Flood season · Boat landings, floating shelters, and elevated rooms support access, refuge, and relief.'}};
$$('[data-season]').forEach(b=>b.addEventListener('click',()=>{setPressed($$('[data-season]'),b);const s=seasons[b.dataset.season];$('#season-image').src=s.src;$('#season-image').alt=s.alt;$('#season-caption').textContent=s.caption;$('#season-zoom').dataset.zoom=s.src}));
const systems={space:{title:'A vertical public realm',text:'Gardens, bridges, reading spaces, and an open ground floor connect the building’s compartments into a continuous civic interior.',zones:[]},structure:{title:'Structure makes room for the city',text:'The mega truss and modular wood grid organise the suspended volumes, keeping a permeable ground plane available for movement and gathering.',zones:[[20,20,68,10],[19,70,72,7]]},climate:{title:'An environmental section',text:'Solar roof systems, cross-atrium ventilation, an adaptive curtain wall, and rainwater capture connect the roof, envelope, and interior gardens.',zones:[[19,17,71,6],[45,27,15,47],[82,30,8,40]]},program:{title:'Knowledge as civic infrastructure',text:'The education block, book stacks, offices, exhibition decks, indoor gardens, and urban living room are linked by a multi-level social spine.',zones:[[22,29,24,41],[62,29,20,41],[20,72,66,14]]}};
$$('[data-layer]').forEach(b=>b.addEventListener('click',()=>{setPressed($$('[data-layer]'),b);const s=systems[b.dataset.layer];$('#system-title').textContent=s.title;$('#system-text').textContent=s.text;$('#section-overlay').replaceChildren(...s.zones.map(z=>{const el=document.createElement('div');el.className='highlight';Object.assign(el.style,{left:z[0]+'%',top:z[1]+'%',width:z[2]+'%',height:z[3]+'%'});return el}))}));
const scenes=$$('[data-scene]');if(scenes.length){const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)$('#journey-current').textContent=e.target.dataset.scene})},{rootMargin:'-20% 0px -40% 0px',threshold:0});scenes.forEach(e=>observer.observe(e))}
const dialog=$('#lightbox');let lastFocus;$$('[data-zoom]').forEach(b=>b.addEventListener('click',()=>{lastFocus=b;const im=dialog.querySelector('img');im.src=b.dataset.zoom;im.alt=b.querySelector('img')?.alt||'Project image';dialog.querySelector('p').textContent=im.alt;dialog.showModal();document.body.style.overflow='hidden'}));dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.addEventListener('close',()=>{document.body.style.overflow='';lastFocus?.focus()});

// Keep the introduction fixed while the portfolio photographs cross-fade.
const hero=$('.hero-carousel');
if(hero){
 const slides=$$('.hero-slide'),dots=$$('[data-slide]'),pause=$('#hero-pause'),reduced=matchMedia('(prefers-reduced-motion: reduce)');
 let current=0,playing=!reduced.matches,timer;
 function showSlide(index){current=(index+slides.length)%slides.length;slides.forEach((s,i)=>s.classList.toggle('is-active',i===current));setPressed(dots,dots[current]);const s=slides[current];$('#hero-title').textContent=s.dataset.title;$('#hero-place').textContent=s.dataset.place;$('#hero-caption').href=s.dataset.href;}
 function schedule(){clearInterval(timer);pause.textContent=playing?'Pause':'Play';pause.setAttribute('aria-label',playing?'Pause slideshow':'Play slideshow');if(playing&&!document.hidden&&!hero.matches(':hover')&&!hero.contains(document.activeElement))timer=setInterval(()=>showSlide(current+1),6500);}
 dots.forEach((b,i)=>b.addEventListener('click',()=>{showSlide(i);schedule()}));pause.addEventListener('click',()=>{playing=!playing;schedule()});
 hero.addEventListener('mouseenter',()=>clearInterval(timer));hero.addEventListener('mouseleave',schedule);hero.addEventListener('focusin',()=>clearInterval(timer));hero.addEventListener('focusout',()=>setTimeout(schedule,0));document.addEventListener('visibilitychange',schedule);reduced.addEventListener('change',()=>{playing=!reduced.matches;schedule()});schedule();
}

// Self-contained world atlas; no tile service, API key, or external scripts.
const atlas=$('#world-map');
if(atlas){
 let box={x:0,y:0,w:1000,h:500},pointers=new Map(),dragged=false;
 const markers=$$('[data-map-marker]');
 function render(){box.w=Math.max(125,Math.min(1000,box.w));box.h=box.w/2;box.x=Math.max(0,Math.min(1000-box.w,box.x));box.y=Math.max(0,Math.min(500-box.h,box.y));atlas.setAttribute('viewBox',`${box.x} ${box.y} ${box.w} ${box.h}`);const z=box.w/1000;markers.forEach(m=>{const base=m.dataset.origin||(m.dataset.origin=m.getAttribute('transform'));m.setAttribute('transform',`${base} scale(${z})`)});$('#map-scale').textContent=(1000/box.w).toFixed(1)+'×';}
 function local(clientX,clientY){const p=new DOMPoint(clientX,clientY);return p.matrixTransform(atlas.getScreenCTM().inverse())}
 function zoom(factor,cx=box.x+box.w/2,cy=box.y+box.h/2){const w=Math.max(125,Math.min(1000,box.w*factor)),f=w/box.w;box={x:cx-(cx-box.x)*f,y:cy-(cy-box.y)*f,w,h:w/2};render()}
 function reset(){box={x:0,y:0,w:1000,h:500};render()}
 $$('[data-map-action]').forEach(b=>b.addEventListener('click',()=>{switch(b.dataset.mapAction){case'in':zoom(.7);break;case'out':zoom(1/.7);break;case'world':reset();break;case'sites':box={x:620,y:120,w:320,h:160};render();break}}));
 atlas.addEventListener('wheel',e=>{if(!e.ctrlKey&&!e.metaKey)return;e.preventDefault();const p=local(e.clientX,e.clientY);zoom(Math.exp(e.deltaY*.002),p.x,p.y)},{passive:false});
 atlas.addEventListener('keydown',e=>{if(e.target!==atlas)return;const step=box.w*.08;if(['+','=','-','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home'].includes(e.key))e.preventDefault();switch(e.key){case'+':case'=':zoom(.7);break;case'-':zoom(1/.7);break;case'ArrowLeft':box.x-=step;render();break;case'ArrowRight':box.x+=step;render();break;case'ArrowUp':box.y-=step;render();break;case'ArrowDown':box.y+=step;render();break;case'Home':reset();break}});
 atlas.addEventListener('pointerdown',e=>{if(e.button!==0)return;dragged=false;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(!e.target.closest('a'))atlas.setPointerCapture(e.pointerId)});
 atlas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const old=pointers.get(e.pointerId),now={x:e.clientX,y:e.clientY};if(Math.hypot(now.x-old.x,now.y-old.y)>2)dragged=true;
 if(pointers.size===2){const other=[...pointers.entries()].find(([id])=>id!==e.pointerId)[1];const d1=Math.hypot(old.x-other.x,old.y-other.y),d2=Math.hypot(now.x-other.x,now.y-other.y);if(d1>0&&d2>0){const p=local((now.x+other.x)/2,(now.y+other.y)/2);zoom(d1/d2,p.x,p.y)}}else{const p1=local(old.x,old.y),p2=local(now.x,now.y);box.x-=p2.x-p1.x;box.y-=p2.y-p1.y;render()}pointers.set(e.pointerId,now)});
 ['pointerup','pointercancel','lostpointercapture'].forEach(type=>atlas.addEventListener(type,e=>pointers.delete(e.pointerId)));
 atlas.addEventListener('click',e=>{if(dragged){e.preventDefault();dragged=false}},true);render();
}
