const $=(s)=>document.querySelector(s),$$=(s)=>[...document.querySelectorAll(s)];
function setPressed(buttons,active){buttons.forEach(b=>b.setAttribute('aria-pressed',String(b===active)))}
$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>{setPressed($$('[data-mode]'),b);$('#visual-view').hidden=b.dataset.mode!=='visual';$('#index-view').hidden=b.dataset.mode!=='index';const u=new URL(location);if(b.dataset.mode==='index')u.searchParams.set('view','index');else u.searchParams.delete('view');history.replaceState(null,'',u)}));
if(new URL(location).searchParams.get('view')==='index')$('[data-mode=index]')?.click();
$$('[data-preview]').forEach(row=>{const show=()=>{if(!matchMedia('(hover:hover) and (min-width:1001px)').matches)return;const p=$('#index-preview');p.src=row.dataset.preview;p.style.display='block'};const hide=()=>$('#index-preview').style.display='none';row.addEventListener('mouseenter',show);row.addEventListener('focus',show);row.addEventListener('mouseleave',hide);row.addEventListener('blur',hide)});
$$('[data-research]').forEach(b=>b.addEventListener('click',()=>{setPressed($$('[data-research]'),b);$('#research-map').hidden=b.dataset.research!=='map';$('#research-index').hidden=b.dataset.research!=='index'}));
const seasons={dry:{src:'assets/jakarta-dry-section.webp',alt:'Dry-season section showing elevated civic platforms and wetland systems',caption:'Dry season · Workshops, kitchens, markets, and gathering spaces form a continuous civic spine.'},flood:{src:'assets/jakarta-flood-section.webp',alt:'Flood-season section showing rising water, floating shelters, and elevated refuge',caption:'Flood season · Boat landings, floating shelters, and elevated rooms support access, refuge, and relief.'}};
$$('[data-season]').forEach(b=>b.addEventListener('click',()=>{setPressed($$('[data-season]'),b);const s=seasons[b.dataset.season];$('#season-image').src=s.src;$('#season-image').alt=s.alt;$('#season-caption').textContent=s.caption;$('#season-zoom').dataset.zoom=s.src}));
const systems={space:{title:'A vertical public realm',text:'Gardens, bridges, reading spaces, and an open ground floor connect the building’s compartments into a continuous civic interior.',zones:[]},structure:{title:'Structure makes room for the city',text:'The mega truss and modular wood grid organise the suspended volumes, keeping a permeable ground plane available for movement and gathering.',zones:[[20,20,68,10],[19,70,72,7]]},climate:{title:'An environmental section',text:'Solar roof systems, cross-atrium ventilation, an adaptive curtain wall, and rainwater capture connect the roof, envelope, and interior gardens.',zones:[[19,17,71,6],[45,27,15,47],[82,30,8,40]]},program:{title:'Knowledge as civic infrastructure',text:'The education block, book stacks, offices, exhibition decks, indoor gardens, and urban living room are linked by a multi-level social spine.',zones:[[22,29,24,41],[62,29,20,41],[20,72,66,14]]}};
$$('[data-layer]').forEach(b=>b.addEventListener('click',()=>{setPressed($$('[data-layer]'),b);const s=systems[b.dataset.layer];$('#system-title').textContent=s.title;$('#system-text').textContent=s.text;$('#section-overlay').replaceChildren(...s.zones.map(z=>{const el=document.createElement('div');el.className='highlight';Object.assign(el.style,{left:z[0]+'%',top:z[1]+'%',width:z[2]+'%',height:z[3]+'%'});return el}))}));
const scenes=$$('[data-scene]');if(scenes.length){const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)$('#journey-current').textContent=e.target.dataset.scene})},{rootMargin:'-20% 0px -40% 0px',threshold:0});scenes.forEach(e=>observer.observe(e))}
const dialog=$('#lightbox');let lastFocus;$$('[data-zoom]').forEach(b=>b.addEventListener('click',()=>{lastFocus=b;const im=dialog.querySelector('img');im.src=b.dataset.zoom;im.alt=b.querySelector('img')?.alt||'Project image';dialog.querySelector('p').textContent=im.alt;dialog.showModal();document.body.style.overflow='hidden'}));dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.addEventListener('close',()=>{document.body.style.overflow='';lastFocus?.focus()});
