from pathlib import Path
from html import escape
import json
D=Path(__file__).parent
projects=[
 dict(id='001',slug='rising-tides',title='Rising Tides,<br>Resilient Lives',name='Rising Tides, Resilient Lives',place='Jakarta, Indonesia',year='2025',field='Water / Collective life',type='Architecture & research',image='jakarta-hero',award='SOM China Fellowship — Winner',question='How can flood-prone infrastructure become a civic sanctuary?',desc='Beneath the Ciliwung River viaduct, a public spine brings wetlands, modular shelters, markets, and elevated walkways into one adaptive system. Architecture supports everyday life while making room for the river to rise.',credit='Individual project · Hao Chang<br>Instructor: Martijn de Geus<br>Kampung Melayu, Jakarta · February–March 2025'),
 dict(id='002',slug='erdai',title='Erdai Art Museum',name='Erdai Art Museum',place='Penghu, Taiwan',year='2024',field='Memory / Landscape',type='Architecture & adaptive reuse',image='erdai-hero',award='',question='How can a landscape of defence become a place of reflection?',desc='A former coastal battery becomes a route through art, ruin, and sea. The museum follows the cliff’s contours and slips beneath the ground, allowing inherited military structures and new cultural spaces to share the same landscape.',credit='Individual studio project · Hao Chang<br>Instructor: Li Xiaodong<br>Penghu, Taiwan · September–October 2024'),
 dict(id='003',slug='spirited-a-way',title='Spirited A Way',name='Spirited A Way',place='Ngari, Tibet',year='2024',field='Ritual / Ecology',type='Architecture & landscape',image='kailash-hero',award='',question='How much architecture does a sacred landscape need?',desc='Along the Mount Kailash pilgrimage route, a courtyard lodge, compact supply stations, and an exhibition hall provide care and orientation. Territorial research guides small interventions that respect both ecological vulnerability and the sequence of ritual.',credit='Collaborative studio · Hao Chang & Mengzhe Lee<br>Hao’s role: research, modeling, renderings, and diagrams<br>Instructor: Yue Cao · November–December 2024'),
 dict(id='004',slug='books-above-bustles',title='Books Above<br>Bustles',name='Books Above Bustles',place='Beijing, China',year='2024',field='Knowledge / Infrastructure',type='Civic architecture',image='books-section',award='',question='Can a library reconnect a city?',desc='Between Chang’an Avenue and the hutongs, a suspended civic building brings reading, learning, and work together above a permeable public ground. A network of gardens, bridges, and shared spaces connects the building’s environmental systems to its social life.',credit='Collaborative studio · Hao Chang & Mengzhe Lee<br>Hao’s role: lead concept, diagrams, modeling, and sections<br>Instructor: Martijn de Geus · April–June 2024'),
 dict(id='005',slug='teaching-building',title='Learning Beyond<br>the Classroom',name='Learning Beyond the Classroom',place='Beijing, China',year='2024–',field='Learning / Adaptive reuse',type='Competition & commission',image='teaching',award='Teaching Building Public Space Competition — 1st Prize',question='What if circulation space became a place to stay?',desc='A proposal for Tsinghua’s teaching spaces transforms underused atriums into flexible settings for social learning. The 2024 competition work is presented here alongside a subsequent commission: co-leading the First Teaching Building renovation commission from May 2025.',credit='Competition proposal: Hao Chang & Mengzhe Lee, 2024<br>Hao’s role: concept, modeling, renderings<br>Instructor: Martijn de Geus<br>Separate commission: First Teaching Building renovation · Co-lead designer · From May 2025'),
 dict(id='006',slug='their-story',title='Their Story',name='Their Story',place='Hong Kong',year='2024',field='Community / Fieldwork',type='Community research',image='their-story',award='',question='How can everyday stories become a shared cultural record?',desc='A community calendar project in Hong Kong’s Eastern District, developed through field research sponsored by Swire Properties. The work brings local stories into a printed format, extending architectural attention toward the people and cultures that give a neighbourhood its character.',credit='Hong Kong Eastern District Community Calendar Project<br>Field research sponsored by Swire Properties<br>August–December 2024'),
 dict(id='007',slug='selected-studies',title='Selected Studies',name='Selected Studies',place='Across media',year='2017–2024',field='Body / Image / Material',type='Art & performance',image='photo',award='',question='Other ways of observing, making, and inhabiting.',desc='Photography, drawing, graphic work, and performance form a parallel practice: experiments in attention, movement, composition, and the spaces between people.',credit='Selected work by Hao Chang<br>Performance photographs document collaborative productions; roles are identified in captions.')]

def img(name,alt,cls='',small=False):
 return f'<img class="{cls}" src="assets/{name}{"-small" if small else ""}.webp" alt="{escape(alt)}" loading="lazy" decoding="async">'
def figure(name,caption,cls=''):
 return f'<figure class="{cls}"><button class="zoom" data-zoom="assets/{name}.webp" aria-label="Enlarge {escape(caption)}">{img(name,caption)}</button><figcaption>{caption}<span>View drawing / image</span></figcaption></figure>'
def heading(n,t,body=''):
 return f'<div class="chapter-heading"><span class="eyebrow">{n}</span><h2>{t}</h2>{"<p>"+body+"</p>" if body else ""}</div>'
def page(name,title,content,active='projects',description='Architecture across changing landscapes, infrastructures, and collective life.'):
 nav=''.join(f'<a href="{url}" {"aria-current=page" if active==key else ""}>{label}</a>' for key,url,label in [('projects','index.html','Projects'),('research','research.html','Research'),('info','info.html','Info')])
 html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} — Hao Chang</title><meta name="description" content="{escape(description)}"><meta name="theme-color" content="#f5f4f0"><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 40 40'%3E%3Crect width='40' height='40' fill='%23151515'/%3E%3Cpath d='M10 9v22m20-22v22M10 20h20' stroke='%23f5f4f0' stroke-width='3'/%3E%3C/svg%3E"><link rel="stylesheet" href="style.css"><script src="app.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="wordmark" href="index.html">HAO CHANG</a><nav aria-label="Main navigation">{nav}</nav></header><main id="main">{content}</main><footer><a class="wordmark" href="index.html">HAO CHANG</a><p>Architecture, research & collective life.</p><a href="mailto:haochang0215@gmail.com">Get in touch</a><span>© 2026 Hao Chang</span></footer><dialog id="lightbox"><button class="close" autofocus aria-label="Close image">Close ×</button><img alt=""><p></p></dialog></body></html>'''
 (D/name).write_text(html)

cards=''
for p in projects:
 cards+=f'<article class="project-card card-{p["id"]}"><a href="{p["slug"]}.html" class="project-image">{img(p["image"],p["name"]+" — "+p["place"],small=True)}</a><div class="card-caption"><span class="eyebrow">{p["id"]}</span><div><h2><a href="{p["slug"]}.html">{p["name"]}</a></h2><p>{p["place"]} <span> / </span> {p["field"]}</p>{"<p class=award>"+p["award"]+"</p>" if p["award"] else ""}</div><span class="year">{p["year"]}</span></div></article>'
rows=''.join(f'<a class="index-row" href="{p["slug"]}.html" data-preview="assets/{p["image"]}-small.webp"><span>{p["id"]}</span><h2>{p["name"]}</h2><span>{p["place"]}</span><span>{p["field"]}</span><span>{p["year"]}</span></a>' for p in projects)
hero_projects=projects[:4]
slides=''.join(f'<div class="hero-slide {"is-active" if i==0 else ""}" data-title="{escape(p["name"])}" data-place="{escape(p["place"])}" data-href="{p["slug"]}.html" aria-hidden="true"><img src="assets/{"books-hero" if i==3 else p["image"]}.webp" alt="" {"fetchpriority=high" if i==0 else "loading=lazy"} decoding="async"></div>' for i,p in enumerate(hero_projects))
dots=''.join(f'<button data-slide="{i}" aria-label="Show {escape(p["name"])}" aria-pressed="{str(i==0).lower()}">{i+1:02}</button>' for i,p in enumerate(hero_projects))
page('index.html','Architecture & Research',f'''<section class="intro hero-carousel" aria-label="Selected work slideshow" aria-roledescription="carousel">{slides}<div class="hero-scrim"></div><div class="hero-copy"><h1>Architecture across<br>changing landscapes,<br>infrastructures, and<br><span>collective life.</span></h1><div class="intro-aside"><p>Hao Chang<br>Architectural designer</p><p>Selected work<br>2024–2025</p></div></div><div class="hero-bottom"><a id="hero-caption" href="rising-tides.html"><span id="hero-title">Rising Tides, Resilient Lives</span><span id="hero-place">Jakarta, Indonesia</span></a><div class="hero-controls">{dots}<button id="hero-pause" aria-label="Pause slideshow">Pause</button></div></div></section><section class="work" id="selected-work"><div class="section-bar"><h2>Selected projects <span>(07)</span></h2><div class="text-switch" aria-label="Project view"><button data-mode="visual" aria-pressed="true">Visual</button><span>/</span><button data-mode="index" aria-pressed="false">Index</button></div></div><div id="visual-view" class="editorial-grid">{cards}</div><div id="index-view" hidden><div class="index-head"><span>No.</span><span>Project</span><span>Place</span><span>Territory</span><span>Year</span></div>{rows}<img id="index-preview" alt="" aria-hidden="true"></div></section><section class="closing"><span class="eyebrow">An ongoing enquiry</span><p>How can architecture hold together<br>ecological change and collective life?</p><a class="line-link" href="research.html">Read the research essays</a></section>''')


for i,p in enumerate(projects):
 content=f'<div class="project-top"><a href="index.html" class="eyebrow">Projects / {p["id"]}</a><h1>{p["title"]}</h1><div class="project-meta"><span>{p["place"]}</span><span>{p["type"]}</span><span>{p["year"]}</span></div></div>{figure(p["image"],p["name"]+" · "+p["place"],"project-hero")}<section class="project-statement"><h2>{p["question"]}</h2><div><p>{p["desc"]}</p>{"<p class=award>"+p["award"]+"</p>" if p["award"] else ""}</div></section>'
 if p['id']=='001':
  content+=f'''<section class="chapter">{heading('01','One structure. Two seasons.','Switch between everyday civic life and flood response. The section keeps the architectural frame constant while revealing changing water levels, access, and use.')}<div class="section-bar"><span class="eyebrow">Seasonal system</span><div class="text-switch"><button data-season="dry" aria-pressed="true">Dry</button><span>/</span><button data-season="flood" aria-pressed="false">Flood</button></div></div><figure><button class="zoom" id="season-zoom" data-zoom="assets/jakarta-dry-section.webp" aria-label="Enlarge seasonal section"><img id="season-image" src="assets/jakarta-dry-section.webp" alt="Dry-season section showing elevated civic platforms and wetland systems"></button><figcaption id="season-caption" aria-live="polite">Dry season · Workshops, kitchens, markets, and gathering spaces form a continuous civic spine.</figcaption></figure><div class="two-images">{figure('jakarta-hero','Dry season · A shaded street for everyday life')}{figure('jakarta-flood','Flood season · Boat access, refuge, and relief')}</div></section><section class="chapter">{heading('02','Water as a collaborator.','The proposal links river restoration, public infrastructure, and community-led construction. Its research considers environmental exposure alongside displacement, livelihoods, and access to services.')}{figure('jakarta-research','Flood research matrix and multi-scalar design framework')}</section><section class="chapter">{heading('03','A system assembled together.','Prefabricated components are paired with community design consultation, cooperative frame assembly, ventilation, rainwater collection, and solar power.')}<div class="narrow-drawing">{figure('jakarta-assembly','Exploded axonometric · Prefabricated, community-assembled dwelling')}</div>{figure('jakarta-long-section','An elevated social spine along the river')}</section>'''
 elif p['id']=='002':
  content+=f'<section class="chapter">{heading("01","An inherited ground.","Bunkers, trenches, and artillery positions become the starting points of a cultural route. Existing structures are retained as spaces for arrival, display, and observation.")}{figure("erdai-map","Historical and natural layers of the Fenggui Peninsula")}</section>'
  scenes=[('erdai-trench','01','Trench','A protected passage becomes the museum’s approach.'),('erdai-gallery','02','Gallery','Compression and low light focus attention inward.'),('erdai-court','03','Courtyard','The route opens to sky, vegetation, and shared space.'),('erdai-chamber','04','Light','A double-height chamber draws daylight into the ground.'),('erdai-hero','05','Sea','The museum returns to the coastal horizon.')]
  content+='<section class="journey"><div class="journey-label"><span class="eyebrow">02 / Spatial sequence</span><h2>From darkness<br>to light.</h2><p id="journey-current" aria-live="polite">01 / Trench</p></div><div class="journey-scenes">'+''.join(f'<figure data-scene="{n} / {t}">{img(a,t)}<figcaption><strong>{n} / {t}</strong>{b}</figcaption></figure>' for a,n,t,b in scenes)+'</div></section>'+figure('erdai-section','Section through memory · Earth, light, and ruin')
 elif p['id']=='003':
  content+=f'''<section class="chapter">{heading('01','The route determines the intervention.','Select a place on the research map to read its architectural response. The three intervention types address different forms of exposure, rest, and cultural interpretation.')}<div class="map-interventions"><div class="annotated-map">{img('kailash-map','Mount Kailash pilgrimage route and architectural intervention locations')}<a class="map-pin pin-a" href="#lodge" aria-label="First Tavern courtyard lodge">A</a><a class="map-pin pin-b" href="#station" aria-label="Supply station">B</a><a class="map-pin pin-c" href="#hall" aria-label="Sky Burial Exhibition Hall">C</a></div><div class="map-legend"><a href="#lodge"><b>A / First Tavern</b><span>Rest · Retrofit · Courtyard</span></a><a href="#station"><b>B / Supply station</b><span>Shelter · Sanitation · Autonomy</span></a><a href="#hall"><b>C / Exhibition hall</b><span>Interpretation · Ritual · Restraint</span></a></div></div></section><section class="chapter" id="lodge">{heading('A','A courtyard for the first night.','The existing inn’s footprint is retained. A new frame, insulated envelope, and shared courtyard support rest while framing the mountain’s north face.')}{figure('kailash-lodge','First Tavern · Courtyard lodge')}</section><section class="chapter" id="station">{heading('B','A compact infrastructure of care.','Prefabricated timber–aluminium modules on elevated piles provide insulated rest and sanitation while reducing ground disturbance.')}<div class="two-images">{figure('kailash-interior','Supply station · Compact interior')}{figure('kailash-research','Religious and ecological vulnerability along the pilgrimage route')}</div></section><section class="chapter" id="hall">{heading('C','Keeping the horizon intact.','Set away from the ritual ground, the exhibition hall uses stone, rammed earth, and timber to introduce interpretation without dominating the landscape.')}{figure('kailash-landscape','Sky Burial Exhibition Hall · Landscape and prayer square')}{figure('kailash-gallery','Sky Burial Exhibition Hall · A sheltered view')}</section>'''
 elif p['id']=='004':
  content+=f'''<section class="chapter">{heading('01','Read the building through its systems.','Select a reading of the section. Highlighted zones locate the systems discussed below; the original drawing remains available at full size.')}<div class="section-bar"><span class="eyebrow">Sectional perspective</span><div class="text-switch layers">{''.join(f'<button data-layer="{x}" aria-pressed="{str(x=="space").lower()}">{x.title()}</button>' for x in ['space','structure','climate','program'])}</div></div><div class="section-explorer">{img('books-section','Sectional perspective through the library and vertical public realm')}<div id="section-overlay" aria-hidden="true"></div></div><div class="system-note" aria-live="polite"><h3 id="system-title">A vertical public realm</h3><p id="system-text">Gardens, bridges, reading spaces, and an open ground floor connect the building’s compartments into a continuous civic interior.</p></div><a class="line-link" href="assets/books-section.webp" target="_blank" rel="noopener">View full-resolution section</a></section><section class="chapter">{heading('02','A civic room above the city.','Suspended volumes open the ground to pedestrian movement and public landscape. The mirrored envelope registers the changing city around it.')}{figure('books-hero','Books Above Bustles · Chang’an Avenue elevation')}</section><section class="chapter">{heading('03','Testing the spatial proposition.','Physical models study the relationship between suspended volumes, structure, light, and the permeable ground.')}{figure('books-model','Physical model · Spatial and structural study')}</section>'''
 elif p['id']=='005':
  content+=f'<section class="chapter">{heading("01","Circulation becomes social space.","The 2024 competition proposal reworks more than 800 square metres of underused atriums. These drawings document that proposal; they are not presented as completed construction or as final documentation of the later commission.")}<div class="two-images">{figure("teaching-plan","2024 competition proposal · Public-space plan")}{figure("teaching-model","2024 competition proposal · Spatial study")}</div></section><section class="project-statement"><h2>From proposal<br>to practice.</h2><p>A subsequent 1,500 m² renovation commission for Tsinghua’s First Teaching Building, co-led from May 2025. The work involves preservation constraints, coordination with university administration, and integrating contemporary building services into the historic fabric.</p></section>'
 elif p['id']=='006':
  content+='<section class="project-statement"><span class="eyebrow">Context</span><p>Developed during the Swire Properties Bi-city Youth Cultural Leadership Programme, this work sits alongside comparative study of urban placemaking and cultural ecosystems in Beijing and Hong Kong.</p></section>'
 else:
  art=[('performance','Cabin Fever · Experimental theatre · Choreographer & director, 2019'),('dance','Shigshir · Mongolian ensemble dance · Tsinghua Dance Troupe, 2021'),('watercolour','Restraint and Observation · Watercolour, 2017'),('ink','Contemplation · Ink, 2017'),('cover','Vers Une Architecture · Book-cover design, 2022'),('photo','Photography · 2024'),('photo-architecture','Photography · 2023'),('still-life','The Sickly Feast · Watercolour, 2017'),('print','The Digital Cage · Printmaking, 2017'),('museum-exhibition','Exhibition design · Hong Kong Palace Museum learning & engagement internship, 2024')]
  content+='<section class="studies-grid">'+''.join(figure(a,b) for a,b in art)+'</section>'
 nxt=projects[(i+1)%len(projects)]
 content+=f'<section class="credits"><h2>Project credits</h2><p>{p["credit"]}</p></section><a class="next-project" href="{nxt["slug"]}.html"><span class="eyebrow">Next project / {nxt["id"]}</span><h2>{nxt["name"]}</h2>{img(nxt["image"],nxt["name"],small=True)}</a>'
 page(p['slug']+'.html',p['name'],content,description=p['desc'])

exec((D/'research-content.py').read_text())

def info_section(title,rows):
 return '<section class="info-section"><h2>'+title+'</h2><div>'+''.join(f'<div class="cv-row"><span>{year}</span><div><h3>{title}</h3><p>{body}</p></div></div>' for year,title,body in rows)+'</div></section>'
info='<section class="page-intro info-intro"><span class="eyebrow">Info / Hao Chang</span><h1>Buildings, landscapes,<br>and the life between.</h1><div class="bio"><p>Hao Chang is an architectural designer whose work explores relationships between ecological change, infrastructure, and collective life. Working across architecture, landscape, and research, he develops spatial systems grounded in the conditions and cultures of a place.</p><p>A graduate of Tsinghua University’s Bachelor of Architecture programme, he received the 2025 SOM China Fellowship for independent research on flood resilience in Jakarta. His experience includes Kohn Pedersen Fox, JJP Architects & Planners, and the Hong Kong Palace Museum, alongside a commissioned campus renovation at Tsinghua.</p><p>Photography, drawing, theatre, and dance extend this practice through other ways of observing and inhabiting space.</p><div class="contact-links"><a class="line-link" href="mailto:haochang0215@gmail.com">haochang0215@gmail.com</a><a class="line-link" href="assets/Hao-Chang-CV.pdf" download>Download CV</a><a class="line-link" href="https://github.com/arc-hao-0215" target="_blank" rel="noopener">GitHub</a></div></div></section>'
info+=info_section('Education',[('2021–2026','Tsinghua University','Bachelor of Architecture · Rank 1/40 · GPA 3.9/4.0'),('2023','National University of Singapore','Exchange programme · September–December')])
info+=info_section('Experience',[('2025–','Tsinghua University','First Teaching Building renovation · Co-lead designer, commissioned<br>1,500 m² adaptive reuse; preservation, building-services integration, and university coordination. '),('2025','Kohn Pedersen Fox · Shanghai','Architecture intern · May–August<br>Mixed-use design development, facade modeling, visualisation, and urban-regeneration research.'),('2024','Hong Kong Palace Museum','Learning & engagement intern · July–August<br>Exhibition logistics, workshops, and public engagement.'),('2023','JJP Architects & Planners · Taipei','Architecture intern · January–February<br>Diagrams and models for aviation and cultural projects.')])
info+=info_section('Selected awards',[('2025','SOM China Fellowship','Winner · Independent research on flood resilience in Jakarta'),('2025','China Habitat Design Annual Award','Gold Medal · Waterfront+ urban design proposal'),('2024','Tsinghua Teaching Building Public Space Competition','1st Prize · Flexible social learning environments')])
info+=info_section('Research & leadership',[('2024','Swire Properties','Bi-city Youth Cultural Leadership Programme · Beijing delegate<br>Urban placemaking strategies and cultural ecosystems.'),('2023','Tsinghua Italy Overseas Research Initiative','Director of public relations · 15-person delegation to Politecnico di Milano<br>Workshops on comparative heritage preservation.'),('2022','World Youth Development Forum','Youth delegate · Dialogue on the UN 2030 Agenda')])
info+=info_section('Publication',[('2025','Architecture Design Studio Series','Contributing author · Tsinghua University faculty publication<br>Selected Year 1 student work.')])
info+='<section class="info-section"><h2>Selected studies</h2><div><p>Performance, photography, drawing, graphic work, and exhibition design.</p><a class="line-link" href="selected-studies.html">Explore the studies</a></div></section>'
page('info.html','Info',info,'info')
(D/'404.html').write_text((D/'index.html').read_text())
print('Generated',len(list(D.glob('*.html'))),'pages')
