# Research essays are editorial readings of the supplied portfolio, not publication claims.
essays=[
 dict(slug='research-water',number='01',title='Adaptation as an everyday practice.',theme='Water / Collective life',place='Jakarta, Indonesia',year='2025',project='rising-tides',image='jakarta-research',caption='Flood research matrix and multi-scalar design framework.',source='Rising Tides, Resilient Lives · Portfolio, pp. 3–9',lon=106.85,lat=-6.2,
 abstract='Flood resilience is often described through the exceptional moment of a disaster. This enquiry begins with the ordinary day: the routes to work, spaces of exchange, and shared services that make a neighbourhood habitable. In Kampung Melayu, the space beneath the Ciliwung River viaduct becomes a test of how these relationships might persist as water levels change.',
 question='How can flood-prone infrastructure support civic life through both dry and flood conditions?',
 method='The portfolio brings territorial flood research, a multi-scalar design framework, and paired seasonal sections into one study. The sections keep a common architectural frame while changing water levels, circulation, and use. This comparison treats time as a spatial variable: a place is read through more than one environmental state.',
 sections=[('Reading exposure together with access','Water is one part of the enquiry. Livelihoods, displacement, public services, and the ability to reach a safe place also shape what resilience means. An elevated platform can address the height of water, but it becomes civic infrastructure only when it connects to daily routines. The research therefore places environmental exposure alongside the relationships that sustain collective life.'),('A section that changes with the season','Clinics, markets, workshops, and gathering spaces establish a public spine in the dry season. Flood conditions recast parts of the same system as refuge, storage, boat access, and relief space. Wetlands and elevated circulation are considered together rather than as separate landscape and building projects. The design proposition is continuity of access, with different forms of occupation as the river rises.'),('From a fixed object to an adaptable system','Modular shelters and a repeatable frame allow the proposal to be understood as a system assembled over time. The architectural enquiry shifts toward the relationship between a durable support and changing needs. These drawings describe a design hypothesis; they do not establish measured flood performance or the outcomes of an implemented community programme.')]),
 dict(slug='research-ground',number='02',title='Ground as an archive.',theme='Memory / Landscape',place='Penghu, Taiwan',year='2024',project='erdai',image='erdai-map',caption='Historical and natural layers of the Fenggui Peninsula.',source='Erdai Art Museum · Portfolio, pp. 24–29',lon=119.57,lat=23.57,
 abstract='A former coastal battery contains more than structures to be preserved. Its trenches, changes of level, and relationship to the sea form a spatial record of defence. This enquiry asks how a museum can make that record legible while opening the site to new cultural life.',
 question='How can architectural intervention reveal an inherited landscape without reducing it to a backdrop?',
 method='The study reads historical and natural layers alongside plans, sections, and a sequence of spatial views. Existing bunkers, trenches, and artillery positions provide reference points for a route. Sectional design examines how buried galleries, open courts, and coastal views can connect inherited ground with new occupation.',
 sections=[('Preservation as a relationship','An isolated remnant can communicate age, yet lose the spatial relationships that made it meaningful. Here, the enquiry extends from individual military structures to the ground between them. A trench is both an inherited trace and a possible approach; the contour is both a physical constraint and an organiser of movement. Reuse begins by asking what these relationships allow a visitor to understand.'),('Sequence as a way of reading','The route moves between compression and release: protected passage, darker gallery, open courtyard, light-filled chamber, and sea. This sequence proposes a way of encountering history through the body. The museum does not rely on a single monumental image. Its meaning develops through duration, changing light, and the alternation between enclosed space and an exposed horizon.'),('An incomplete archive','New galleries slip beneath the ground while existing structures remain participants in the route. The proposition is not to restore a single historical moment, but to make different layers available to contemporary use. The portfolio records a design interpretation of the site; claims about visitor experience or conservation performance would require further investigation.')]),
 dict(slug='research-ritual',number='03',title='An infrastructure of care.',theme='Ritual / Ecology',place='Mount Kailash, Ngari',year='2024',project='spirited-a-way',image='kailash-research',caption='Religious and ecological vulnerability along the pilgrimage route.',source='Spirited A Way · Portfolio, pp. 10–17',lon=81.31,lat=31.07,
 abstract='A pilgrimage route is simultaneously a cultural sequence, a demanding journey, and an ecologically vulnerable landscape. Around Mount Kailash, the question of intervention is also a question of restraint: where can architecture provide care, and where should it recede?',
 question='How can essential shelter and services support a sacred journey while respecting its landscape and ritual sequence?',
 method='Territorial mapping and research into ecological and religious vulnerability guide the placement and character of interventions. GIS-based study is read together with the experience of the route. The portfolio develops three responses—a courtyard lodge, compact supply stations, and an exhibition hall—to examine different forms of rest, exposure, and interpretation.',
 sections=[('The route precedes the building','The enquiry begins with movement through a landscape rather than a freestanding programme. Needs change along the journey, as do the cultural meanings of particular places. This makes location, visibility, and the scale of an intervention part of the research question. A building is considered through its relationship to a longer sequence, not only through its own plan.'),('Different forms of care','At the First Tavern, the existing footprint becomes the basis for a courtyard lodge that supports rest and shared space. Supply stations explore compact, insulated shelter and sanitation with reduced ground disturbance. The exhibition hall is set away from the ritual ground, using its position and material character to approach interpretation with restraint. These are related responses, but they are not interchangeable.'),('Restraint as an architectural criterion','The study uses the provision of essential services to test how much architecture is needed. Retaining footprints, concentrating facilities, and protecting views become ways to limit the intervention’s presence. The proposal remains a design study: environmental performance and cultural acceptance cannot be inferred from drawings alone. Those questions would need continued engagement and site-specific assessment.')]),
 dict(slug='research-civic',number='04',title='Knowledge as civic infrastructure.',theme='Knowledge / Public life',place='Beijing, China',year='2024',project='books-above-bustles',image='books-section',caption='Sectional perspective through the library and vertical public realm.',source='Books Above Bustles · Portfolio, pp. 18–23',lon=116.4,lat=39.9,
 abstract='A library can be read as a collection of rooms, but also as an arrangement of relationships between knowledge and public space. Between Chang’an Avenue and the hutongs, this enquiry tests whether a civic building can connect urban movement, shared learning, and environmental systems through its section.',
 question='What can the section of a library reveal about the relationship between public access, structure, and collective life?',
 method='Sectional perspectives, programme studies, and physical models investigate suspended volumes and a permeable ground. The same section is read through spatial, structural, climatic, and programmatic relationships. This method makes it possible to consider the systems together while examining what each contributes to public occupation.',
 sections=[('Public space beyond the ground floor','The open ground establishes a connection with pedestrian movement. Above it, gardens, bridges, reading spaces, and shared rooms extend the idea of a public interior vertically. The enquiry concerns the continuity between these spaces: whether moving through the building can also become an encounter with learning and other people.'),('Structure as a civic decision','Suspended volumes and a large spanning structure are not only questions of engineering expression. They determine what can remain open beneath the building and how programmes relate across it. Physical models test the spatial proposition alongside the sectional drawings. Structure becomes one of the means by which a civic room is made available to the city.'),('Reading environmental and social systems together','Solar roof systems, ventilation, rainwater capture, and interior gardens are considered within the same architectural section as reading and gathering spaces. The resulting drawings propose relationships rather than measured outcomes. The research contribution lies in the method of reading the building as an interconnected civic and environmental system; operational performance would need separate verification.')])
]

# Equirectangular world land geometry, Natural Earth public-domain 1:110m dataset.
land=json.loads((D/'assets/world-land.geojson').read_text())
paths=[]
for f in land['features']:
 g=f['geometry']; polys=g['coordinates'] if g['type']=='MultiPolygon' else [g['coordinates']]
 for poly in polys:
  paths.append(' '.join('M'+'L'.join(f'{(lon+180)*1000/360:.2f},{(90-lat)*500/180:.2f}' for lon,lat,*_ in ring)+'Z' for ring in poly))
svg='<svg id="world-map" viewBox="0 0 1000 500" tabindex="0" role="group" aria-label="World research map. Plus and minus zoom; arrow keys pan; Home resets." aria-describedby="map-help"><g class="graticule">'
for x in range(0,1001,83): svg+=f'<path d="M{x} 0V500"/>'
for y in range(0,501,83): svg+=f'<path d="M0 {y}H1000"/>'
svg+='</g><g class="world-land">'+''.join(f'<path d="{path}"/>' for path in paths)+'</g><g class="map-markers">'
for e in essays:
 x=(e['lon']+180)*1000/360;y=(90-e['lat'])*500/180
 svg+=f'<a href="{e["slug"]}.html" aria-label="{e["place"]}: {e["title"]}" data-map-marker transform="translate({x:.3f} {y:.3f})"><circle class="marker-hit" r="11"/><circle r="4"/><text x="8" y="-8">{e["number"]}</text><title>{e["place"]} — {e["title"]}</title></a>'
svg+='</g></svg>'
rows=''.join(f'<a class="research-row" href="{e["slug"]}.html"><span>{e["number"]}</span><h2>{e["title"]}</h2><span>{e["theme"]}</span><span>{e["place"]}</span></a>' for e in essays)
previews=''.join(f'<article class="essay-preview"><div class="essay-meta"><span class="eyebrow">{e["number"]} / {e["theme"]}</span><p>{e["place"]}<br>{e["year"]} · Design research</p></div><div><h2><a href="{e["slug"]}.html">{e["title"]}</a></h2><p class="essay-abstract">{e["abstract"]}</p><p class="essay-question"><span>Research question</span>{e["question"]}</p><a class="line-link" href="{e["slug"]}.html">Read essay ↗</a></div></article>' for e in essays)
page('research.html','Research',f'''<section class="page-intro"><span class="eyebrow">Research / An ongoing enquiry</span><h1>Reading places.<br>Tracing relationships.</h1><p>Research begins before the architectural proposal and continues through it. These essays trace the questions, methods, and ideas behind the work—across water, memory, ritual, and public life.</p></section><section><div class="section-bar"><h2>Territories of enquiry <span>04 studies</span></h2><div class="text-switch"><button data-research="map" aria-pressed="true">Map</button><span>/</span><button data-research="index" aria-pressed="false">Index</button></div></div><div id="research-map" class="research-map"><div class="map-canvas">{svg}<div class="map-heading"><span class="eyebrow">Field atlas / 2024–2025</span><span>WGS 84 · World</span></div><div class="map-controls" aria-label="Map controls"><button data-map-action="in" aria-label="Zoom in">+</button><button data-map-action="out" aria-label="Zoom out">−</button><button data-map-action="world">World</button><button data-map-action="sites">Research sites</button></div><span id="map-scale" aria-live="polite">1.0×</span></div><div class="map-caption"><p id="map-help">Drag to pan · Pinch or use + / − to zoom · Select a numbered site to read</p><a href="https://www.naturalearthdata.com/" target="_blank" rel="noopener">Basemap: Natural Earth</a></div><div class="atlas-key">{''.join(f'<a href="{e["slug"]}.html"><span>{e["number"]}</span>{e["place"]}</a>' for e in essays)}</div></div><div id="research-index" hidden>{rows}</div></section><section class="research-essays" aria-label="Research essays">{previews}</section><p class="research-note">Design research essays developed from the selected portfolio. Project pages document the architectural proposals, drawings, and credits.</p>''','research')
for e in essays:
 content=f'<article class="research-article"><header class="essay-header"><a class="eyebrow" href="research.html">Research / Essay {e["number"]}</a><h1>{e["title"]}</h1><div class="essay-byline"><span>{e["theme"]}</span><span>{e["place"]} · {e["year"]}</span><span>Design research</span></div></header><div class="essay-layout"><aside><span class="eyebrow">Contents</span><nav aria-label="Essay contents"><a href="#abstract">Abstract</a><a href="#question">Research question</a><a href="#method">Method</a>'+''.join(f'<a href="#section-{i}">{title}</a>' for i,(title,body) in enumerate(e['sections']))+f'</nav><a class="line-link" href="{e["project"]}.html">View related project ↗</a></aside><div class="essay-body"><section id="abstract"><h2>Abstract</h2><p class="abstract-text">{e["abstract"]}</p></section><section id="question"><h2>Research question</h2><p class="question-text">{e["question"]}</p></section><section id="method"><h2>Method</h2><p>{e["method"]}</p></section>'+''.join(f'<section id="section-{i}"><h2>{title}</h2><p>{body}</p></section>' for i,(title,body) in enumerate(e['sections']))+f'<section class="essay-source"><h2>Source & context</h2><p>{e["source"]}. This essay is an editorial reading of the project research presented in the portfolio. Project authorship, collaborators, and instructors are credited on the related project page.</p><a class="line-link" href="{e["project"]}.html">Explore the architectural proposal ↗</a></section></div></div>{figure(e["image"],e["caption"],"essay-figure")}<a class="line-link" href="research.html">← All research essays</a></article>'
 page(e['slug']+'.html',e['title'],content,'research',e['abstract'])
